- Applications/App/qAppMainWindow.cxx
- CMake/Superbuild/External_Slicer.cmake
Before testing this pull request, please make sure to delete the SlicerSALT.ini file pointed to by `SlicerSALT --settings-path` output.
> ENH: Changing the module bar

- Applications/App/Main.cxx
- CMake/Superbuild/External_ShapePopulationViewer.cmake
Changes shape population viewer tag to compensate for a bug that was fixed
Fixes bug for crash when SlicerSALT without window.
> Minor fixes

- Applications/App/qAppMainWindow.cxx
- CMakeLists.txt
- Modules/Scripted/CMakeLists.txt
- Modules/Scripted/ShapeAnalysisToolBox/CMakeLists.txt
- Modules/Scripted/ShapeAnalysisToolBox/CommonUtilities/__init__.py
- Modules/Scripted/ShapeAnalysisToolBox/CommonUtilities/utility.py
- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
- Modules/Scripted/ShapeAnalysisToolBox/Resources/DataImporter.ui
Data importer right now can:
* Load labelmap segmentations in a given cohort
* Iterate over subjects and their individual segmentations
* Perform topology checks.
> FEAT: WIP adding data importer as a scripted module

- CMakeLists.txt
The name of the extension is Skeletal Representation Visualizer
Closes #46
> ENH: Add SRepExtension

- .gitignore
> ENH: Add gitignore

- CMakeLists.txt
> ENH: Add extensions: merge models and surfacetoolbox

- Applications/SlicerSALTApp/qSlicerSALTAppMainWindow.cxx
The resolution for high dpi is untested, but at least
it solves the low resolution problem for regular dpi.
More info: https://github.com/KitwareMedical/SlicerCustomAppTemplate/issues/6
Fix #66
> BUG: Fix resolution of logo for non high dpi

- CMakeLists.txt
Update to latest master.
`git shortlog --no-merges d649bc812a4e90d16ae8ab4e4c23d166d775f4cd..3307e8c221052d65c4e2909881b926f956227f12`
Zhiyuan (4):
for the purpose of creating extension index
qtcreator temp file
fix
delete irrelevant file
> COMP: Rename SRepExtension to SlicerSkeletalRepresentation

- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
When the topology is not a simple topology (CIRCLE, TORUS, etc)
shows the topologyNumber (-512, -42, ...), and assign them to a new
topology type: MULTIPLE_HOLES.
Reported by @bpanigua
> ENH: DataImporter, handle topologies with multiple holes.

- SuperBuild/External_SPHARM-PDM.cmake
> ENH: Update SPHARM

- SuperBuild/External_ModelToModelDistance.cmake
- SuperBuild/SlicerPackageExtensions.cmake
Upstream: https://github.com/NIRALUser/3DMetricTools
master branch at: dbd3b88a2e98320abcb4282f4ee146bc11f5c991
Fixes #128
> ENH: Add ModelToModelDistance module

- CMakeLists.txt
The latest version of the SRep module implements initialization and visualization of s-reps.
> update the latest commit tag of skeletal representation module

- Applications/SlicerSALTApp/qSlicerSALTAppMainWindow.cxx
- CMakeLists.txt
- Modules/Scripted/Home/Home.py
for reference, the changes associated with (1) are the following:
```
MFSDA
* MFSDA module
- title   :   MSFDA -> Covariate Significance Testing
- category: Pvalues -> Shape Analysis
* MFSDA_createShapes module
- category: PValues -> Shape Analysis.Advanced
* MFSDA_run module
- category: PValues -> Shape Analysis.Advanced
ShapeVariationAnalyzer
* ShapeVariationAnalyzer module
- title   : ShapeVariationAnalyzer -> Population Analysis
- category:          Decomposition -> Shape Analysis
* shapepca module
- category:          Decomposition -> Shape Analysis.Advanced
* shapepcalib module
- category:          Decomposition -> Shape Analysis.Advanced
shape4D
* shape4D module
- category: Shape Analysis -> Shape Analysis.Advanced
ShapePopulationViewer
* Extension metadata
- EXTENSION_CATEGORY: …
```
> Organize SlicerSALT module list

- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
- Modules/Scripted/ShapeAnalysisToolBox/Resources/DataImporter.ui
> Dataimporter update

- Applications/SlicerSALTApp/slicer-application-properties.cmake
> ENH: Begin 2.0 Development

- Applications/SlicerSALTApp/slicer-application-properties.cmake
Going forward We will be using odd number for preview/development,
even for release
closes #187
> Begin Slicer SALT 2.1 development

- CMakeLists.txt
```
Jared Vicory (2):
ENH: Refactor MFSDA Extension GUI
BUG: Fix crash from mismatched matrix dimensions
```
Closes #181
> ENH: Update MFSDA_Python repository (#181)

- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
- Multi-subject selection now works correctly
- Tables are cleared when closing the scene
- Users can now specify which subject to use as the consistency template
Closes #178 
Closes #179 
Closes #180
> Data Importer fixes and updates

- Applications/SlicerSALTApp/slicer-application-properties.cmake
> ENH:  Begin SlicerSALT 2.3 Development

- CMakeLists.txt
> BUG:  Fixed SPHARM-PDM layout

- CMakeLists.txt
- Modules/Scripted/Home/CMakeLists.txt
- Modules/Scripted/Home/Home.py
- Modules/Scripted/Home/Resources/SampleDataDescription/MFSDAInputData.json
- Fixes bug reported in discourse
- Adds sample data for MFSDA
> MFSDA updates

- CMakeLists.txt
Update SVA to include @lbumbolo additions to the module
> ENH: Update SVA tag

- CMakeLists.txt
- Modules/Scripted/Home/Home.py
I also cleaned up handling of output directories with the sample data autofill code.
> Update MFSDA to remove spherical template

- CMakeLists.txt
```
Jared Vicory (1):
COMP: Remove unused references to Testing directories
```
> COMP: Update RBC to fix build failures with testing on 

- CMakeLists.txt
Adding the initial version of the Procrustes alignment module
> ENH: Add procrustes module

- CMakeLists.txt
$ git shortlog 02e56a2...203bd9a --no-merges
Ye Han (2):
ENH: Control signifi figs, fix shaking sliders, use std for sliders and projection
ENH: Transform model to LPS coordinate by default
> ENH: SVA usability improvements

- BUILD.md
- README.md
@bpaniagua 
The draft document `TESTING.md` would need some more work to list all extension included in SlicerSALT.
Thinking more about it, this type of list should like go in the SlicerSALT wiki and only be linked from the README.
> Reorganize and update readme

- CMakeLists.txt
Adding SRep2 extension to SlicerSALT
> ENH: Add SRep2 extension

- CMakeLists.txt
> COMP: Update SlicerSRep2 extension

- Modules/Scripted/Home/Home.py
The website link was correct, but the module name it was attached to was wrong.
> BUG: Fix tutorial link for SPHARM-PDM Correspondence Improvement

- Applications/SlicerSALTApp/qSlicerSALTAppMainWindow.cxx
- CONTRIBUTING.md
- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
- Modules/Scripted/ShapeAnalysisToolBox/Resources/DataImporter.ui
> DOC: Fix various typos

- CMakeLists.txt
- Modules/Scripted/Home/CMakeLists.txt
- Modules/Scripted/Home/Home.py
- Modules/Scripted/Home/Resources/SampleDataDescription/CrownSegmentation.json
Add SlicerDentalModelSeg Fly-by-CNN work for segmenting and numbering teeth from intra-oral scans.
> ENH: Add SlicerDentalModelSeg extension (#258)

- CMakeLists.txt
- Modules/Scripted/Home/CMakeLists.txt
- Modules/Scripted/Home/Home.py
- Modules/Scripted/Home/Resources/SampleDataDescription/SlicerDWDInputData.json
Adds extension to superbuild.
Sets up extension sample data.
Sets up extension tutorial link.
Co-authored-by: David Allemang <david.allemang@kitware.com>
> ENH: Add SlicerDWD extension

- CMakeLists.txt
- Modules/Scripted/Home/Home.py
Updates to latest Slicer. (This was an attempt to fix https://github.com/Kitware/SlicerSALT/issues/283, but more work is needed. Likely the final fix will involve another Slicer update, so these changes are still good.)
Fixes https://github.com/Kitware/SlicerSALT/issues/284
> Update slicer and fix bug

- Applications/SlicerSALTApp/qSlicerSALTAppMainWindow.h
- CMakeLists.txt
This is a draft for SlicerSalt that includes the new Pipeline Creator and Runner plus the Combined Create and Enhance module. Barring bugs this should enable you to run the module through the new Pipeline case iterator. 
Neither the SRep branch used here nor the Pipelines branch is fully merged into the respective repositories
> Create and Enhance Pipeline Module

- CMakeLists.txt
For https://github.com/slicersalt/RegistrationBasedCorrespondence/pull/7
> COMP: Upgrade RegistrationBasedCorrespondence

- CMakeLists.txt
> 20241106 module updates

- CMakeLists.txt
Adds module based on PhD work of Kedar Madi: https://github.com/kedar-codes/hippo_morph
> ENH: Add DifferenceStatistics module (#331)

- CMakeLists.txt
Update SPHARM to include the recent changes by @allemangD
> ENH: Update SPHARM-PDM tag (#306)

- CMakeLists.txt
https://github.com/slicersalt/SPHARM-PDM/commits/slicersalt-2025-04-23-94720ec9c/
https://github.com/NIRALUser/SPHARM-PDM/pull/89
> COMP: Update SPHARM-PDM: Support MSVC

- Modules/Scripted/Home/Home.py
@bpaniagua Looks like we missed converting a couple of the slide decks into markdown (they were newer and probably not listed on the website). I can work on that this weekend.
> DOC: Update doc links to point to readthedocs

- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
ExportSegmentsToModelHierarchy was removed in Slicer so we should be using ExportSegmentsToModels instead. I also put the color node removal in a try block as it is not always there (I'm not sure if it ever is anymore but it shouldn't hurt to keep it as is)
Crash was reported here: https://discourse.slicer.org/t/slicer-salt-having-trouble-with-generate-shape-analysis-structure/42827
> BUG: Fix crash due to deprecated functionality
