- CMake/Superbuild/External_SPHARM-PDM.cmake
- Modules/Scripted/ShapeAnalysisToolBox/CommonUtilities/utility.py
- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
The issue was mostly due to a naming conflict with the directory CommonUtilities that SPHARM-PDM also have and erase during the packaging of SlicerSALT. The solution was to make the two codes in the utility file similar.
> Fixing of Data Importer Module

- CMake/Superbuild/CMakeLists.txt
- CMake/Superbuild/External_ShapeRegressionExtension.cmake
- CMake/Superbuild/External_Slicer.cmake
- CMake/Superbuild/External_SlicerPackageExtensions.cmake
ENH: Adding of Shape Regression extension containing two modules:
- RegressionComputation: Computation of time-regressed shapes in a collection of 3D shape inputs associated to a linear variable.
This module uses shape4D CLI: https://github.com/laurapascal/shape4D
- RegressionVisualization:
* Plot the time-regressed shape volume according to the linear variable
* Visualize the sequence of the time-regressed shapes generated
This module uses Sequences and SampleData Extension
> ENH: Adding of Shape Regression extension

- SuperBuild/External_ShapeRegressionExtension.cmake
Date: 2018-08-31
https://github.com/KitwareMedical/ShapeRegressionExtension/tree/c550e279da633906344dd7b4ae86425e536ca853
`git shortlog --no-merges dbfbae5e1478a502ade903910862959aa..c550e279da63390634`
```
James Fishbaugh (12):
Added correct affiliation for James Fishbaugh.
Time Parameters section: changed t0 and tn to doubles and minor changes to layout.
ENH: Time Parameters section: changed t0 and tn to doubles and minor changes to layout.
ENH: Added default values for shape kernel width and deformation kernel width, computed as 50% of the smallest dimension of the axis-aligned bounding box around each shape.
ENH: Deformation Parameters section: Kernel width changed to double, regularity weight set with a default value of 0.01, and some minor formatting fixes.
ENH: Output Parameters …
```
> ENH: Update ShapeRegressionExtension

- CMakeLists.txt
Needed in the last update of SRepExtension
https://github.com/KitwareMedical/SRepExtension/tree/d649bc812a4e90d16ae8ab4e4c23d166d775f4cd
`git shortlog --no-merges  df8b732c1..d649bc812a4`
```
Pablo Hernandez-Cerdan (1):
COMP: Use find_package(Eigen3)
Zhiyuan (6):
add test_data
add template of loadable module: initializer
pause loadable module since libigl uses c++11 features
add forward flow with default params
finish ui of conventional foward flow
move inkling flow and modify ui
bp (1):
ENH: Add new s-rep icon
```
> COMP: Update SRepExtension with Eigen3 dependency

- CMakeLists.txt
Includes the fix to use Eigen either with find_package
or with add_subdirectory.
Branch: https://github.com/jcfr/eigen-git-mirror/tree/slicersalt-3.3-2018-09-07-2fd9e7447
PR upstream: https://github.com/eigenteam/eigen-git-mirror/pull/10
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
> BUG: Update Eigen to be found with add_subdirectory

- CMakeLists.txt
This commit updates the source directory of SlicerSkeletalRepresentation
extension from SlicerSkeletalRepresentation to SRep
Fixes #74
> COMP: Attempt to fix path too long windows error

- CMakeLists.txt
Fixes #78
```
$ git shortlog bfb31b7..ba967ad --no-merges
cmake: Fix bundling of the extension adding dependency to RigidAligment and SurfRemesh
```
> COMP: Update GROUPS extension to fix build

- CMakeLists.txt
Fixes missing dirent.h and M_PI definitions for both GROUPS and RigidAlignment via these commits:
https://github.com/vicory/GROUPS/commit/e85dd4f2dad796aaa06212f10bea7eea769db639
https://github.com/vicory/RigidAlignment/commit/6545c99d5d301912e6f9471eb21754b4846b92d9
> COMP: Update GROUPS to fix Windows build

- CMakeLists.txt
This commit really fix #72. The issue was originally closed assuming that
Slicer r27379 (BUG: Ensure python-packaging is available) was the fix.
$ git shortlog 0998e2912..b6764a60f --no-merges
jcfr (1):
[Backport] COMP: Fix build when extension manager support is disabled
> BUG: Update to Slicer to fix packaging import error

- CMakeLists.txt
Fixes #89
$ git shortlog b6764a60f..109d50f88 --no-merges
jcfr (1):
[backport] BUG: Fix start menu shortcut of installed custom Slicer application
> BUG: Fix window menu shortcut name for installation of SlicerSALT

- SuperBuild/External_SPHARM-PDM.cmake
`git shortlog --no-merges  08eaaed1f13..808d62926dfd`
```
Pablo Hernandez-Cerdan (1):
BUG: Fix header resize to be compatible with qt4 and qt5
```
> BUG: Update SPHARM, fix compatibility with qt5

- CMakeLists.txt
- SuperBuild/External_SPHARM-PDM.cmake
List of GROUPS changes:
$ git shortlog 47ae184..c2aeef9 --no-merges
cmake: Update LAPACK external project to always log configuration and build
List of SPHARM-PDM changes:
$ git shortlog 808d629..d3f8b24 --no-merges
cmake: Update LAPACK external project to fix macOS and Linux build error
> cmake: Update GROUPS and SPHARM-PDM to use the same LAPACK external project

- SuperBuild/External_ShapePopulationViewer.cmake
$ git shortlog deb14cdca..724374c --no-merges
Jean-Christophe Fillion-Robin (3):
cmake: Fix windows configuration failure
cmake: Remove support for building against ITKv3
cmake: Remove obsolete code
> COMP: Update ShapePopulationViewer to fix windows configuration error

- SuperBuild/External_ShapePopulationViewer.cmake
Fixes #103
$ git shortlog 724374c..d8d75f1 --no-merges
COMP: Fix windows build error due to missing includes
> COMP: Update ShapePopulationViewer to fix windows build error

- CMakeLists.txt
$ git shortlog cd7d51ce9b..9e3e45ae9ae --no-merges
Jared Vicory (2):
ENH: Update NumPy to 1.15.1
ENH: Patch NumPy to allow building SciPy using flang
Jean-Christophe Fillion-Robin (3):
[Backport Slicer/Slicer#1022] COMP: Support packaging of extension from within Slicer custom application
[Backport Slicer/Slicer#1022] COMP: Support packaging of libraries outside of Slicer or extension build tree
[Backport Slicer/Slicer#1022] COMP: Support non-superbuild extension that define CPACK_INSTALL_CMAKE_PROJECTS
cpinter (8):
COMP: Fix build on Qt4/VTK7
BUG: Fixed Pick3D initialization in displayable managers
BUG: Fix default display and storage node creation
BUG: Fix 3D picking in displayable managers
ENH: Consider default display node on SH visibility change
STYLE: Fix typos in …
> ENH: Update to Slicer 4.11-2018-11-08-94fb4a634

- CMakeLists.txt
This PR integrates https://github.com/jcfr/RigidAlignment/commit/dacd7ca503e3cf7a4a3301e5901e756acc978cca
It fixes the following build error introduced by NIRALUser/RigidAlignment@7f0ac80(BUG: Fix Windows crash on array allocation):
```
In file included from /usr/include/c++/5/vector:62:0,
from ./RigidAlignmentCLP.h:8,
from /path/to/SlicerSALT/RigidAlignment/RigidAlignment.cxx:11:
/usr/include/c++/5/bits/stl_construct.h: In instantiation of ‘void std::_Destroy(_Tp*) [with _Tp = std::__cxx11::basic_string<char> [250]]’:
/usr/include/c++/5/bits/stl_construct.h:103:19:   required from ‘static void std::_Destroy_aux<<anonymous> >::__destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::__cxx11::basic_string<char> (*)[250]; bool <anonymous> = false]’ …
```
> COMP: Update GROUPS to fix RigidAlignement unix build error due to invalid array

- CMakeLists.txt
BUG: Fix casting issue in python wrappings generated in SkeletalRepresentation
Fix #142
Update SkeletalRepresentation to master.
```
git shortlog --no-merges 027a1b8a..7be23feb
Pablo Hernandez-Cerdan (3):
COMP: Fix warnings in vtkBackwardFlowLogic
STYLE: Remove unused macros, fix indent
COMP: Avoid running the mock test in SkeletalRepresentationVisualizer
lopezmt (1):
FIX: casting issue with vtkBackwardFlowLogic and vtkForwardFlowLogic
```
Also, use SRep as a short_extension_name to avoid long path problems on Windows.
> BUG: Fix casting issue in python wrappings generated in SkeletalRepresentation

- CMakeLists.txt
- Modules/Scripted/ShapeAnalysisToolBox/DataImporter.py
$ git shortlog 9cb1e8107..e71081e8c --no-merges
Jean-Christophe Fillion-Robin (3):
[Backport Slicer/Slicer#1022] COMP: Support packaging of extension from within Slicer custom application
[Backport Slicer/Slicer#1022] COMP: Support packaging of libraries outside of Slicer or extension build tree
[Backport Slicer/Slicer#1022] COMP: Support non-superbuild extension that define CPACK_INSTALL_CMAKE_PROJECTS
jcfr (5):
ENH: Install pip independently of extension manager support
BUG: Update CTK to include DICOM display fields and python manager fixes
COMP: Update CTK including expected PythonQt version
BUG: Do not report error when logging message in ScriptedLoadableModuleWidget.cleanup
BUG: Ensure logged messages are handled during application destruction
lassoan (2):
BUG: …
> BUG: Update Slicer to fix DataImporter error on application exit

- CMakeLists.txt
* Since JsonCpp is now a requirements of VolumeRendering module, the JsonCpp library will now be built and packaged.
* Explicitly set Slicer_CPACK_NSIS_INSTALL_REQUIRES_ADMIN_ACCOUNT to ON to maintain current installation behavior. See Slicer r28293 (ENH: Allow Slicer install on Windows for non-admin users)
> ENH: Update Slicer

- CMakeLists.txt
Updates SPHARM-PDM to fix python 3-related errors
Fixes one of the issues identified in #167
> ENH: Update SPHARM-PDM to support Python 3

- CMakeLists.txt
```
$ git shortlog 59eb810..90d8bdc --no-merges
BUG: Add support for editing gradient point color. See NIRALUser/ShapePopulationViewer#43
```
> BUG: Add support for editing gradient color in ShapePopulationViewer

- CMakeLists.txt
```
$ git shortlog 344ced6b1..933a0785f --no-merges
cpinter (17):
BUG: Fix setting volume property for multivolume in volume rendering
BUG: Remove SH harden transform question if changing transform on single item
BUG: Fix crash when closing application after certain operations in SH
ENH: Allow handling events by interaction context
STYLE: Add function for default context name in markups display node
ENH: Improve volume visibility options in subject hierarchy
BUG: Fix opacity function for segmentations in subject hierarchy
ENH: Add reset field of view action for showing volumes in SH
ENH: Optimize UI of Models and Markups modules
ENH: Rename overwrite-related masking options in Segment Editor
ENH: Update CTK hash to include DICOM database fix
BUG: Fix subject hierarchy …
```
> ENH: Update Slicer to integrate updated SurfaceToolbox module. See #182

- CMake/CMakeLists.txt
- CMakeLists.txt
Updated FindFortran module to correctly include libomp.dll
Module updated in SALT, GROUPS, and SPHARM-PDM
Fixes #138
> BUG:  Fixed Windows Fortran packaging

- Modules/Scripted/Home/Resources/SampleDataDescription/SPHARM-PDMTestData.json
The sample data json for SPHARM was downloading all the test data, making the module run both the inputs and the outputs as inputs. This PR corrects that problem.
cc: @sjh26 @vicory please review and merge
> BUG: Correct Sample Data SPHARM

- CMakeLists.txt
Closes #211 
Pulls in this patch commit for Slicer: https://github.com/slicersalt/Slicer/commit/1a6cdcc3a271e6608d2125830a1e832e490047be
> Fix Windows Packaging

- CMakeLists.txt
- Modules/Scripted/Home/CMakeLists.txt
- Modules/Scripted/Home/Home.py
- Modules/Scripted/Home/Resources/SampleDataDescription/SPHARM-PDMFiducials.json
- Modules/Scripted/Home/Resources/SampleDataDescription/SPHARM-PDMTestData.json
There are associated branches in the GROUPS, SPHARM-PDM, and RigidAlignment repositories as well. This commit updates the tags that SlicerSALT refers to.
https://github.com/slicersalt/GROUPS/tree/slicersalt-2020-06-09-4b2d735
https://github.com/slicersalt/SPHARM-PDM/tree/slicersalt-2020-06-09-60d892b
https://github.com/slicersalt/RigidAlignment/tree/slicersalt-2020-06-09-9386fdb
RigidAlignment is pulled in through GROUPS; a similar update has been made there.
> Update GROUPS and SPHARM-PDM

- CMakeLists.txt
These updates fix the QPainterPath include bug which prevents compiling on macOS with Qt 5.15
> Update SlicerSALT for Qt 5.15

- CMakeLists.txt
Closes #228
Slicer:
````
$ git shortlog fdcc0aa...8a9b7043
[backport] COMP: Fix configuration with CMake >= 3.17
````
> COMP: Fix configuration with CMake >= 3.17

- CMakeLists.txt
Jared Vicory (1):
ENH: Rename files to fix Windows compilation issues
Jean-Christophe Fillion-Robin (12):
COMP: Refiner: Fix build error using nullptr
COMP: Refiner: Fix build error using "std::abs" instead of "abs"
COMP: Refiner: Fix unused-variable and unused-parameter warnings
COMP: Refiner: Fix sign-compare warnings
COMP: Refiner: Fix -Wmaybe-uninitialized warnings in vtkPolyData2ImageData
COMP: Refiner: Use nullptr and override keywords
COMP: Initializer: Fix unused-variable warning
COMP: Refiner: Fix object name in UI file
STYLE: Remove trailing whitespaces
STYLE: Expand tabs into four spaces
Merge pull request #29 from jcfr/cleanup-whitespaces
Merge branch 'misc-tweaks'
Zhiyuan (1):
Add support for converting SALT srep to legacy sreps
Zhiyuan Liu (20):
Improve …
> ENH: Update s-rep extension

- Applications/SlicerSALTApp/qSlicerSALTAppMainWindow.cxx
- CMakeLists.txt
- Modules/Scripted/Home/Home.py
@bpaniagua 
This updates to the Slicer stable, with no modifications yet.  The only build issue is SPHARM-PDM (error below).  We had previously addressed this by not using ITK 5, but we should go ahead and get this fixed now.  I have most of the changes needed (I think) on this branch here:  https://github.com/slicersalt/SPHARM-PDM/commits/slicersalt-2020-04-27-47188484c
SALT is currently using this less recent branch:   https://github.com/slicersalt/SPHARM-PDM/commits/slicersalt-2018-11-29-4baa99c10
Should I go ahead and try to resolve these branches?
````
D:\D\E\SA-2-build\ITK\Modules\Core\Common\include\itkExceptionObject.h(19): fatal error C1189: #error:  "Do not include itkExceptionO
bject.h directly,  include itkMacro.h instead." (compiling source file …
```
> Update Slicer to 4.11.20200930 Stable

- CMakeLists.txt
Jared Vicory (4):
Fix bug causing strange s-rep meshes
Add module to allow initializing s-reps from SPHARM models
ENH: Update SPHARM initialization
BUG: Fix Mac compilation error
vicory (2):
Merge pull request #42 from vicory/add_spharm_code
Merge pull request #43 from vicory/add_spharm_code
> ENH: Update s-rep repo

- CMakeLists.txt
@bpaniagua @vicory Please review and merge/upload to data.kitware.com if this works. I will publish the blog after that.
Meanwhile I got the following build error this morning which is due to the testing data website down. 
`CMake Error at /home/yehan/Kitware/SlicerSALT-build/slicersources-src/CMake/ExternalData.cmake:1113 (message):
Object MD5=3666cc8160c47307192f6d895574a390 not found at:
https://github.com/Slicer/SlicerTestingData/releases/download/MD5/3666cc8160c47307192f6d895574a390 ("HTTP response code said error")
http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=3666cc8160c47307192f6d895574a390 (wrong hash MD5=50928178198297b8e2a3a58e2af4c7ba)
http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=3666cc8160c47307192f6d89 …
> ENH: Update SVA and Procrustes repo

- CMakeLists.txt
This is just a temporary fix until we can move MeshToLabelMap testing data that used to be on midas.
> Temporarily disable MeshToLabelMap testing

- CMakeLists.txt
0552f19 updates all the git tags to the most-recent branch in the corresponding [slicersalt fork](https://github.com/slicersalt/). 
The other commits update those modules which had upstream changes (ModelToModelDistance, Shape4D, ShapePopulationViewer, and SPHARM-PDM). For each of those modules I pulled the latest upstream, then rebased the tag referenced in 0552f19 onto that. See the commit messages for the new upstream changes. Something like:
```
$ git checkout origin/<latest branch>
$ git checkout -b "slicersalt-$(date -I)-$(git rev-parse --short upstream/master)"
$ git rebase -i upstream/master
$ git push -u origin <current branch>
```
Resolves #240.
> Update SALT Modules

- CMakeLists.txt
Fixes LPS/RAS inversion
Fixes build of tests that previously failed to download test data.
> BUG: Update version of MeshToLabelMap with bug fixes

- CMakeLists.txt
On March 15, 2022 git stopped accepting clones via the unencrypted git
protocol.
This commits changes to use https:// instead of git://
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> BUG: Fix use of deprecated unencrypted git protocol

- CMakeLists.txt
Easier use of SRep as polydata.
Fixes python wrapping on a couple methods.
> ENH: Update SlicerSRep2 extension

- CMakeLists.txt
GROUPS changes: git shortlog --no-merges 1263afc12..387bc83ad
Connor Bowley (2):
BUG: Fix running with new vtk files
BUG: Update RigidAlignment
> BUG: Update GROUPS

- CMakeLists.txt
Integrates https://github.com/slicersalt/RegistrationBasedCorrespondence/pull/5 to support more file formats.
> COMP: Upgrade RegistrationBasedCorrespondence

- CMakeLists.txt
$ git shortlog --no-merges f7418f7ad3bf69cafac9871ce7d2f9adfa7cdfd1..bd5e394ecf6a2f944e998d3f76c8125fc648e8a1 Jared Vicory (2):
ENH: Use combined bounding box for registration
ENH: Fix vtk/vtp errors with SPV
> ENH: Update RBC

- Docs/modules/SurfacePlaneMapper.md
ReadTheDocs the SurfacePlaneMapper module
> SurfacePlaneMapper.md

- CMakeLists.txt
Based of the following commits:
* KitwareMedical/SlicerCustomAppTemplate@bdcb062f6
`COMP: Set Slicer_MACOSX_BUNDLE_GUI_IDENTIFIER`
* Slicer/Slicer@4425da860
`COMP: Fix application notarization on macOS setting bundle identifier`
Since the `slicer-macos-codesign-scripts` can be locally modified to force the update of the identifier [^1], this is not required for the current `4.0.1` release of SlicerSALT.
[^1]: https://github.com/KitwareMedical/slicer-macos-codesign-scripts/pull/1
> COMP: Fix macOS notarization setting Slicer_MACOSX_BUNDLE_GUI_IDENTIFIER
